### ISSUE TITLE
Minio Support

### ISSUE THREAD

**Issue by iot-resister** [single-spa/import-map-deployer#84]
Just wanted to share. I got this working as it is similar to digital ocean spaces: 

`config.json`
```json

{
  "manifestFormat": "importmaps",
  "s3Endpoint": "https://<selfhosted.domain>",
  "locations":{
    "default": "spaces://minio.<selfhosted.domain>/import-map.json"
  }
}
```
`docker-compose.yml`
```yml
version: "3.7"
services:
  import-map-deployer:
    image: singlespa/import-map-deployer
    ports:
      - 5000:5000
    environment:
      AWS_ACCESS_KEY_ID: $MINIO_ID
      AWS_SECRET_ACCESS_KEY: $MINIO_SECRET
    volumes:
      - ./config.json:/www/config.json
```
